=== josuehernandez-15/HCKT-CLOUD/DataGenerator/schemas-validation/empleados.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Empleados",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "empleado_id"
  },
  "properties": {
    "empleado_id": { "type": "string" },

    "nombre": { "type": "string" },

    "tipo_area": { 
      "type": "string",
      "enum": [
        "mantenimiento",
        "electricidad",
        "limpieza",
        "seguridad",
        "ti",
        "logistica",
        "otros"
      ]
    },

    "estado": {
      "type": "string",
      "enum": ["activo", "inactivo"]
    },

    "contacto": {
      "type": "object",
      "properties": {
        "telefono": { "type": "string" },
        "correo": { "type": "string", "format": "email" }
      },
      "required": [],
      "additionalProperties": false
    }
  },

  "required": ["empleado_id", "nombre", "tipo_area", "estado"],
  "additionalProperties": false
}

=== josuehernandez-15/HCKT-CLOUD/DataGenerator/example-data/empleados.json
[
  {
    "empleado_id": "ea1cdcd3-97bc-4c7f-87c4-3933612ab240",
    "nombre": "María García",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 955420362",
      "correo": "maría.garcía@outlook.com"
    }
  },
  {
    "empleado_id": "6453c388-a9ba-49ac-bdce-924db783ee7a",
    "nombre": "Sofía Castro",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 947157622",
      "correo": "sofía.castro@gmail.com"
    }
  },
  {
    "empleado_id": "a90d30e1-0138-4030-a110-e3e9d8d5f892",
    "nombre": "Luis Rodríguez",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 984503321",
      "correo": "luis.rodríguez@outlook.com"
    }
  },
  {
    "empleado_id": "061a548f-a86f-4248-bc2e-8700c4162dfe",
    "nombre": "Juan Pérez",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 956512071",
      "correo": "juan.pérez@gmail.com"
    }
  },
  {
    "empleado_id": "85e1893a-d4f3-4c31-90ff-fea98afd1a03",
    "nombre": "Pedro Flores",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 947598811",
      "correo": "pedro.flores@utec.edu.pe"
    }
  },
  {
    "empleado_id": "3ddd5539-b452-4d84-9666-1131b8e7010e",
    "nombre": "Ana Martínez",
    "tipo_area": "mantenimiento",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 910163416",
      "correo": "ana.martínez@outlook.com"
    }
  },
  {
    "empleado_id": "a5a71940-5a76-4f64-992a-6637a66f7e74",
    "nombre": "Isabel Ramírez",
    "tipo_area": "mantenimiento",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 997901898",
      "correo": "isabel.ramírez@outlook.com"
    }
  },
  {
    "empleado_id": "b4ae49ca-0668-457b-b8b5-2248854944b1",
    "nombre": "Juan Pérez",
    "tipo_area": "mantenimiento",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 946696436",
      "correo": "juan.pérez@utec.edu.pe"
    }
  },
  {
    "empleado_id": "7c2e6130-7a2f-44e2-9002-0f59a944ee8c",
    "nombre": "José González",
    "tipo_area": "electricidad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 951121698",
      "correo": "josé.gonzález@outlook.com"
    }
  },
  {
    "empleado_id": "2f6abe31-9018-48f9-baf3-68671563b4a1",
    "nombre": "Carmen Fernández",
    "tipo_area": "electricidad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 955348518",
      "correo": "carmen.fernández@gmail.com"
    }
  },
  {
    "empleado_id": "51e02440-71e8-486d-bbaa-e31bde3fb702",
    "nombre": "Andrés Silva",
    "tipo_area": "electricidad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 966228867",
      "correo": "andrés.silva@utec.edu.pe"
    }
  },
  {
    "empleado_id": "89d2e65f-7da0-404f-80e3-41ebc933d604",
    "nombre": "Laura Sánchez",
    "tipo_area": "electricidad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 952912422",
      "correo": "laura.sánchez@gmail.com"
    }
  },
  {
    "empleado_id": "27d92b42-a6bb-4786-9b33-834f24d49e49",
    "nombre": "Andrés Silva",
    "tipo_area": "electricidad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 998987809",
      "correo": "andrés.silva@gmail.com"
    }
  },
  {
    "empleado_id": "0dd7e2a4-1b9c-459a-a286-57a3bca4f723",
    "nombre": "Carlos López",
    "tipo_area": "electricidad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 971625212",
      "correo": "carlos.lópez@gmail.com"
    }
  },
  {
    "empleado_id": "c7d2bf58-eca2-456b-91c3-eb1e39a0bb3e",
    "nombre": "Diego Morales",
    "tipo_area": "electricidad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 914311228",
      "correo": "diego.morales@utec.edu.pe"
    }
  },
  {
    "empleado_id": "90e587d0-d054-48e2-bed4-ed35dd020e72",
    "nombre": "Luis Rodríguez",
    "tipo_area": "limpieza",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 979820097",
      "correo": "luis.rodríguez@outlook.com"
    }
  },
  {
    "empleado_id": "74c81489-a613-447c-92c5-130eae9befba",
    "nombre": "José González",
    "tipo_area": "limpieza",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 925112660",
      "correo": "josé.gonzález@gmail.com"
    }
  },
  {
    "empleado_id": "2182e4e4-56d0-4383-8cce-9d44476eab94",
    "nombre": "Valentina Ortiz",
    "tipo_area": "limpieza",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 954032308",
      "correo": "valentina.ortiz@gmail.com"
    }
  },
  {
    "empleado_id": "aabf73e7-062b-4507-9838-a1e0b50d0127",
    "nombre": "Andrés Silva",
    "tipo_area": "limpieza",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 910826435",
      "correo": "andrés.silva@utec.edu.pe"
    }
  },
  {
    "empleado_id": "eb86266c-7e8d-4c9d-941c-3218d30d944b",
    "nombre": "Carmen Fernández",
    "tipo_area": "limpieza",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 920515245",
      "correo": "carmen.fernández@utec.edu.pe"
    }
  },
  {
    "empleado_id": "d5d12b34-8a32-46fd-8b6a-14f5b5598dcc",
    "nombre": "José González",
    "tipo_area": "limpieza",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 997867901",
      "correo": "josé.gonzález@gmail.com"
    }
  },
  {
    "empleado_id": "a70116ef-1413-470c-ba26-bd4fdc9f0143",
    "nombre": "Andrés Silva",
    "tipo_area": "limpieza",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 914407886",
      "correo": "andrés.silva@outlook.com"
    }
  },
  {
    "empleado_id": "dc6b8a43-b612-42e7-8195-a46f7aeeb0a0",
    "nombre": "Juan Pérez",
    "tipo_area": "seguridad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 948412539",
      "correo": "juan.pérez@utec.edu.pe"
    }
  },
  {
    "empleado_id": "0e7eb088-9cd2-4fb9-b7f7-b64c937d0391",
    "nombre": "Isabel Ramírez",
    "tipo_area": "seguridad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 948929611",
      "correo": "isabel.ramírez@outlook.com"
    }
  },
  {
    "empleado_id": "8a4d3e1a-e757-4842-a35d-85a7e51a4da0",
    "nombre": "Diego Morales",
    "tipo_area": "seguridad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 976868875",
      "correo": "diego.morales@outlook.com"
    }
  },
  {
    "empleado_id": "92c0e3b4-1b50-44a5-9cae-9aa3a6a8a074",
    "nombre": "Carmen Fernández",
    "tipo_area": "seguridad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 922628540",
      "correo": "carmen.fernández@utec.edu.pe"
    }
  },
  {
    "empleado_id": "1d283ed5-5d5d-48e1-aae8-4b31dd5de2a0",
    "nombre": "Miguel Torres",
    "tipo_area": "seguridad",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 974789102",
      "correo": "miguel.torres@outlook.com"
    }
  },
  {
    "empleado_id": "84ba3225-2de8-4dea-95ad-78a6fd569d13",
    "nombre": "Pedro Flores",
    "tipo_area": "seguridad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 988505227",
      "correo": "pedro.flores@gmail.com"
    }
  },
  {
    "empleado_id": "0c662758-d761-455a-94dd-3d14eca5fd15",
    "nombre": "Juan Pérez",
    "tipo_area": "seguridad",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 993518398",
      "correo": "juan.pérez@outlook.com"
    }
  },
  {
    "empleado_id": "e0b17bab-f6bd-4862-bdeb-d7d146c4e4ab",
    "nombre": "Camila Rojas",
    "tipo_area": "ti",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 957019267",
      "correo": "camila.rojas@gmail.com"
    }
  },
  {
    "empleado_id": "12ca89e7-2b7b-4aa7-b585-0ee0ee6148ea",
    "nombre": "Miguel Torres",
    "tipo_area": "ti",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 977520421",
      "correo": "miguel.torres@outlook.com"
    }
  },
  {
    "empleado_id": "a291e0b5-18aa-4dea-9a8a-b8c416bcc18d",
    "nombre": "Valentina Ortiz",
    "tipo_area": "ti",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 990264851",
      "correo": "valentina.ortiz@utec.edu.pe"
    }
  },
  {
    "empleado_id": "920d130d-9c47-47bf-bdd9-559ff6bb2cad",
    "nombre": "Juan Pérez",
    "tipo_area": "ti",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 947342953",
      "correo": "juan.pérez@outlook.com"
    }
  },
  {
    "empleado_id": "bc2bbfa3-041e-41a3-93b9-e18fa569da9a",
    "nombre": "Carmen Fernández",
    "tipo_area": "ti",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 917279433",
      "correo": "carmen.fernández@outlook.com"
    }
  },
  {
    "empleado_id": "199a5256-223f-4641-b0d7-940652330267",
    "nombre": "Sofía Castro",
    "tipo_area": "ti",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 960513258",
      "correo": "sofía.castro@utec.edu.pe"
    }
  },
  {
    "empleado_id": "3dd8dce6-a981-44bf-9196-d57a5693fa7f",
    "nombre": "José González",
    "tipo_area": "ti",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 969593188",
      "correo": "josé.gonzález@gmail.com"
    }
  },
  {
    "empleado_id": "270a10a7-471f-40fd-9f50-50ea08ab2db7",
    "nombre": "Andrés Silva",
    "tipo_area": "logistica",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 977049471",
      "correo": "andrés.silva@utec.edu.pe"
    }
  },
  {
    "empleado_id": "8e45eb2d-f1d0-4f0e-8686-115330d08915",
    "nombre": "Carlos López",
    "tipo_area": "logistica",
    "estado": "inactivo",
    "contacto": {
      "telefono": "+51 980390155",
      "correo": "carlos.lópez@gmail.com"
    }
  },
  {
    "empleado_id": "dd0b1af0-4d8f-49c3-b041-cb623b00626c",
    "nombre": "Carmen Fernández",
    "tipo_area": "logistica",
    "estado": "activo",
    "contacto": {
      "telefono": "+51 971230479",
      "correo": "carmen.fernández@utec.edu.pe"
    }
  },
  {
