=== josuehernandez-15/HCKT-CLOUD/DataGenerator/schemas-validation/usuarios.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Usuarios",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "usuario_id"
  },
  "properties": {
    "usuario_id": { "type": "string" },
    "correo": {
      "type": "string",
      "format": "email"
    },
    "contraseña": { "type": "string" },
    "nombre": { "type": "string" },
    "rol": {
      "type": "string",
      "enum": ["estudiante", "personal_administrativo", "autoridad"]
    }
  },
  "required": ["usuario_id", "correo", "nombre", "rol", "contraseña"],
  "additionalProperties": false
}

=== josuehernandez-15/HCKT-CLOUD/DataGenerator/example-data/usuarios.json
[
  {
    "usuario_id": "587afc36-cb80-4cee-be07-6bff4fb96436",
    "correo": "camila.rojas@outlook.com",
    "contraseña": "hash_0b351f5c609f49f4",
    "nombre": "Camila Rojas",
    "rol": "personal_administrativo"
  },
  {
    "usuario_id": "10a9700c-76fb-4edd-9869-641c86e4a416",
    "correo": "isabel.ramírez@gmail.com",
    "contraseña": "hash_6dab0d0cb124489f",
    "nombre": "Isabel Ramírez",
    "rol": "estudiante"
  },
  {
    "usuario_id": "91ce8ccb-2c3d-4e6d-8473-961fd77dd845",
    "correo": "camila.rojas@outlook.com",
    "contraseña": "hash_985d0841465b4985",
    "nombre": "Camila Rojas",
    "rol": "autoridad"
  },
  {
    "usuario_id": "fbc1f17a-7bac-426b-b6dc-5c03966f03eb",
    "correo": "diego.morales@utec.edu.pe",
    "contraseña": "hash_3f9db61fb03c4e05",
    "nombre": "Diego Morales",
    "rol": "autoridad"
  },
  {
    "usuario_id": "ed487f36-0093-4286-987c-83b4aa93abf7",
    "correo": "maría.garcía@gmail.com",
    "contraseña": "hash_0b4e495d012f4143",
    "nombre": "María García",
    "rol": "personal_administrativo"
  },
  {
    "usuario_id": "01b9ced3-43f4-4cff-a363-5cc319944f3c",
    "correo": "sofía.castro@outlook.com",
    "contraseña": "hash_456131b8506e45ce",
    "nombre": "Sofía Castro",
    "rol": "personal_administrativo"
  },
  {
    "usuario_id": "f318768f-611e-4acb-baad-f4410f9a1c70",
    "correo": "ana.martínez@utec.edu.pe",
    "contraseña": "hash_778959d59e0646a8",
    "nombre": "Ana Martínez",
    "rol": "personal_administrativo"
  },
  {
    "usuario_id": "50ab0a8d-a77e-421b-b713-e60b1b00485e",
    "correo": "josé.gonzález@utec.edu.pe",
    "contraseña": "hash_0fd03d917bab4781",
    "nombre": "José González",
    "rol": "personal_administrativo"
  },
  {
    "usuario_id": "e8f181c6-9479-4bc8-aa36-e53494557c43",
    "correo": "isabel.ramírez@utec.edu.pe",
    "contraseña": "hash_03b1e5972e434d7f",
    "nombre": "Isabel Ramírez",
    "rol": "autoridad"
  },
  {
    "usuario_id": "5e37b837-847c-458c-969d-e76b54cb1bd1",
    "correo": "juan.pérez@gmail.com",
    "contraseña": "hash_ebae4e99d8b74e62",
    "nombre": "Juan Pérez",
    "rol": "autoridad"
  }
]
